### ISSUE TITLE
What is the time dealy for each DM?

### ISSUE THREAD

**Issue by nicolaieg** [hbollon/IGopher#5]
I saw that is a waiting time? is it random for a period? does it still work if I minimize tray in taskbar or does it need to be on the screen?

**Comment by hbollon** [comment]
Hi! 
Indeed, there is a random waiting period between each DM. This, moreover, for all interactions with Instagram such as after changing page, looking for a user, typing a key on the keyboard etc.
This in order to make the bot's behavior as close as possible to that of a human. Of course all these waiting times are more or less long depending on the interaction and ensure maximum performance but keeping optimal security for your account.

As for running the bot through the WebDriver, you can minimize the window the bot will continue to run. However, you can also use the **--headless** flag by launching _IGopher_ (GUI or TUI version) to use a frame buffer and therefore do without any browser window!
The bot is under development, this option will be accessible directly via the interface in the future. For the moment, you must go through this flag to use this functionality.
