### ISSUE TITLE
Javascript Error at initializing, before login in

### ISSUE THREAD

**Issue by nicolaieg** [hbollon/IGopher#6]
https://ibb.co/ZM1tghN

**Comment by nicolaieg** [comment]
<div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 1026.56px; color: rgb(34, 34, 34); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class=""><div id=":on" class="ii gt" style="font-size: 0.875rem; direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative;"><div id=":om" class="a3s aiL " style="overflow: hidden; font: small / 1.5 Arial, Helvetica, sans-serif;"><div dir="ltr">
error | unknown error - 33: Unable to create session from { "desiredCapabilities": { "browserName": "chrome", "chromeOptions": { "binary": ".\\lib\\chrome-win\\chrome.exe", "args": [ "--disable-extensions", "--disable-infobars", "--no-sandbox", "--window-size=360,640" ], "mobileEmulation": { "deviceName": "Nexus 5" }, "w3c": false }, "goog:chromeOptions": { "binary": ".\\lib\\chrome-win\\chrome.exe", "args": [ "--disable-extensions", "--disable-infobars", "--no-sandbox", "--window-size=360,640" ], "mobileEmulation": { "deviceName": "Nexus 5" }, "w3c": false } }, "capabilities": { "firstMatch": [ { "browserName": "chrome", "goog:chromeOptions": { "binary": ".\\lib\\chrome-win\\chrome.exe", "args": [ "--disable-extensions", "--disable-infobars", "--no-sandbox", "--window-size=360,640" ], "mobileEmulation": { "deviceName": "Nexus 5" }, "w3c": false } } ] } } Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53' System info: host: 'DESKTOP-NM7GOV4', ip: '192.168.1.115',&nbsp;os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1' Driver info: driver.version: unknown | 2021-05-24T19:30:23+03:00
-- | -- | --
warning | Error renaming ".\\lib\\chromedriver_win32\\chromedriver.exe" to ".\\lib\\chromedriver.exe": rename .\lib\chromedriver_win32\chromedriver.exe .\lib\chromedriver.exe: Access is denied. | 2021-05-24T19:29:44+03:00
info | Downloading and installing dependencies... | 2021-05-24T19:29:40+03:00

</div><div class="yj6qo"></div><div class="adL"></div></div></div><div class="hi" style="border-bottom-left-radius: 1px; border-bottom-right-radius: 1px; padding: 0px; width: auto; background: rgb(242, 242, 242); margin: 0px;"></div></div></div><br class="Apple-interchange-newline">

**Comment by hbollon** [comment]
According to the logs, the dependency manager cannot move one of the dependencies due to lack of rights.
Where do you have installed IGopher? In a directory where your user has rights?
Can you delete the **lib** subfolder and relaunch IGopher via a terminal located in the installation folder and with the flag: _-- loglevel=debug_ (something like this: ```./IGopher.exe --loglevel=debug```) please?

I think you can work around this problem by running IGopher as administrator but it's not normal to have to do this, check that the whole installation folder is not read-only and that the regular users have write permission (security tab in the folder's property window).

For information, the dependency download tracking is not yet integrated into the graphical interface but is done well when you launch the bot via the launch button (this is why it may take a little time to start the first time depending on your internet connection). This should change for the next patch which is coming soon. (you can check the patch's roadmap here: https://github.com/hbollon/IGopher/projects/3)
However, there are loading bars for tracking downloads in the terminal which you can normally view by launching IGopher.exe from the terminal or through the TUI.
