### ISSUE TITLE
Error handling chrome-linux.zip

### ISSUE THREAD

**Issue by ShiroiCho** [hbollon/IGopher#8]
**Describe the bug**

**To Reproduce**
1. Launch TUI version of IGopher.
2. Configure account credentials.
3. Launch!
**Expected behavior**
For it to download the dependencies and launch,

**Screenshots**
[Image](https://imgur.com/a/CkY9oQV)
**Error output**

🦄 Welcome to IGopher, the (soon) most powerful and versatile Instagram bot!

> 🚀 - Launch!
  🔧 - Configure
  🧨 - Reset settings
  🚪 - Exit

INFO[0001] Downloading and installing dependencies...    function=DownloadDependencies line=279
selenium-server.jar:      0.00 b / 0.00 b [----------------------------------------------------------| 0s ] 0.00 b/s
sauce-connect.tar.gz:     0.00 b / 0.00 b [----------------------------------------------------------| 0s ] 0.00 b/s
chrome-linux.zip:         0.00 b / 0.00 b [----------------------------------------------------------| 0s ] 0.00 b/s
chromedriver.zip:         0.00 b / 0.00 b [----------------------------------------------------------| 0s ] 0.00 b/s
firefox-nightly.tar.bz2:  0.00 b / 0.00 b [----------------------------------------------------------| 0s ] 0.00 b/s
htmlunit-driver.jar:      0.00 b / 0.00 b [----------------------------------------------------------| 0s ] 0.00 b/s
geckodriver.tar.gz:       0.00 b / 0.00 b [----------------------------------------------------------| 0s ] 0.00 b/s
FATA[0003] Error handling chrome-linux.zip: Error unzipping "./lib/chrome-linux.zip": exit status 9  function=func1 line=342

**Desktop**
 - OS: Ubuntu 16.04
 - Version 0.2.2

**Additional context**
Running on google cloud.

**Comment by hbollon** [comment]
Hi mate! 
For unzipping, IGopher dependency manager use **_unzip_** program on Linux/MacOS which is normally installed with your OS. 
Check its presence on your system, if it is missing install it (`sudo apt install unzip` on Ubuntu) and restart IGopher with the flag `--force-download`.

Otherwise it may be a problem of rights, check that the installation directory or one of the sub-folders has the correct rights and retry (also with the `--force-download` flag to trigger the reinstallation)

**Comment by ShiroiCho** [comment]
That made it go past the original error, but now I get:

INFO[0001] Downloading and installing dependencies...    function=DownloadDependencies line=279
selenium-server.jar: done!       
sauce-connect.tar.gz: done!      
chrome-linux.zip: done!          
chromedriver.zip: done!          
firefox-nightly.tar.bz2: done!   
htmlunit-driver.jar: done!       
geckodriver.tar.gz: done!        
ERRO[0031] unknown error: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location ./lib/chrome-linux/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=94.0.4597.0 (40326849aff98c8735579ca74d80816d2d2dd93f-refs/heads/master@{#907986}),platform=Linux 4.15.0-1098-gcp x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 171 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'instance-1', ip: '10.128.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1098-gcp', java.version: '1.8.0_292'
Driver info: driver.version: unknown  function=InitChromeWebDriver line=143
INFO[0031] Reached end of service. Sleeping...           function=CheckTime line=130

**Comment by hbollon** [comment]
I deployed a fix on `fix-8-chrome` branch, it should solve your issue. 
I prepared two executable for you (both GUI and TUI versions since I don't know which one you used), can you give it a try?
You must do a fresh installation since I upgraded chrome/chromedriver versions and the dependency manager is not able to do the upgrades himself atm.

Download links: https://drive.google.com/drive/folders/1ZOVuCV4VWX148Rb4p1ZcQOqgkMuIlTzL?usp=sharing

Keep me updated :smile:

**Comment by hbollon** [comment]
Hi @ShiroiCho, have you been able to try the patch? If so, did it solve your problem?

**Comment by hbollon** [comment]
Since I don't have any feedback from you and seeing that all the tests with the patch on my side were conclusive, I consider that it is fixed and I merge the fix in patch 0.3.0.
If your problem persists **with the new patch** and after **a complete reinstallation**, do not hesitate to reopen this issue. :wink:
